//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmongDogUs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmongDogUs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Modが有効になっているため、&lt;br&gt;クイックチャットのみのプレイは不可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChatInfoDesc {
            get {
                return ResourceManager.GetString("ChatInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラープル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorBlurple {
            get {
                return ResourceManager.GetString("ColorBlurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワインレッド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorBordeaux {
            get {
                return ResourceManager.GetString("ColorBordeaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットピンク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorHotPink {
            get {
                return ResourceManager.GetString("ColorHotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorIce {
            get {
                return ResourceManager.GetString("ColorIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベンダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorLavender {
            get {
                return ResourceManager.GetString("ColorLavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レモン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorLemon {
            get {
                return ResourceManager.GetString("ColorLemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorMint {
            get {
                return ResourceManager.GetString("ColorMint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヌガー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorNougat {
            get {
                return ResourceManager.GetString("ColorNougat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オリーブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorOlive {
            get {
                return ResourceManager.GetString("ColorOlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピーチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorPeach {
            get {
                return ResourceManager.GetString("ColorPeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペトロルブルー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorPetrol {
            get {
                return ResourceManager.GetString("ColorPetrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーモン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorSalmon {
            get {
                return ResourceManager.GetString("ColorSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   山吹色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorSignalOrange {
            get {
                return ResourceManager.GetString("ColorSignalOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンライズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorSunrise {
            get {
                return ResourceManager.GetString("ColorSunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ティール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorTeal {
            get {
                return ResourceManager.GetString("ColorTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターコイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorTurqoise {
            get {
                return ResourceManager.GetString("ColorTurqoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワサビ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorWasabi {
            get {
                return ResourceManager.GetString("ColorWasabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modが有効になっているため、&lt;br&gt;公開ルームは利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableOnlineText {
            get {
                return ResourceManager.GetString("DisableOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AmongDogUs Ver.{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionShower {
            get {
                return ResourceManager.GetString("VersionShower", resourceCulture);
            }
        }
    }
}
